# prod version, should be used with common config file
version: '2'
# TODO: try to use volumes instead of mount
services:
    # receive http connection from client
    web:
        ports:
            - 9899:80
            - 9898:443
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
    lb:
        ports:
            - 1936:1936
